export { SmoothScroll, useLenis, useScrollLock, type SmoothScrollProps } from './smooth-scroll';
export { SplitReveal, useSplitReveal, refreshScroll, type SplitRevealProps, type SplitRevealOptions } from './split-reveal';
export { CaslHeading, type CaslHeadingProps, type DisplaySize } from './casl-heading';
export { Magnetic, type MagneticProps } from './magnetic';
export { Marquee, type MarqueeProps } from './marquee';
export { Reveal, Parallax, type RevealProps, type ParallaxProps } from './reveal';
export { stagger } from './stagger';
export { CountUp, type CountUpProps } from './count-up';
export { TickingDigits, type TickingDigitsProps } from './ticking-digits';
export { HighlightSwipe, type HighlightSwipeProps } from './highlight-swipe';
export { shapeConfetti, shapeConfettiCannons, type ShapeConfettiOptions } from './shape-confetti';
export { gsap, ScrollTrigger, SplitText, useGSAP, EASE } from './gsap';
export { usePointer, pointer, type PointerState } from '@/lib/hooks/use-pointer';
export { useReducedMotion } from '@/lib/hooks/use-reduced-motion';
export { useInViewport } from '@/lib/hooks/use-in-viewport';
